### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by esperantgada** [google-developer-training/android-basics-kotlin-lunch-tray-app#11]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
I just need help in fragment_entree_menu_xml

**Describe the problem**

android:checked="@{viewModel.entree.equals(viewModel.menuItems["cauliflower"].name)}"
android:onClick="@{() -> viewModel.setEntree(viewModel.menuItems["cauliflower"].name'

This is how I tried to set checked and onClick attribut for this view but it didn't work. Please, I need help.
Thanks in advance for your helps.

**Comment by alu0100207385** [comment]
Hi esperantgada,
I had the same problem and I did this:
`
android:onClick='@{() -> viewModel.setEntree("cauliflower")}'
android:checked='@{viewModel.entree.name.equals(viewModel.menuItems["cauliflower"].name)}'
`
I hope it was useful for you.

**Comment by esperantgada** [comment]
Thank you very much. It works.

**Comment by esperantgada** [comment]
Hello sir, I hope you're doing great.

Thank you so much for your help. It works. I'm really glad.

See you soon!!

**Comment by gouravkhunger** [comment]
Hey @alu0100207385, I don't think we actually need `android:checked` parameter. Since they are in a radio group they are bound to only have 1 radio button checked at once. `android:onClick` works fine in that case too.

**Comment by wgoodey** [comment]
> I don't think we actually need `android:checked` parameter.

Not setting `android:checked` introduces a small bug where if you go back to the start page via the back button instead of the cancel button, previously selected items aren't pre-selected when you come back to the radio groups. Otherwise, if you don't go back to the start page it seems to work fine.

**Comment by DemisChan** [comment]
@esperantgada i believe you should change the outer double quotes to single.
`android:checked='@{viewModel.entree.equals(viewModel.menuItems["cauliflower"].name)}'`
