### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by Clod** [google-developer-training/android-basics-kotlin-lunch-tray-app#13]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
3) Get started -> Under title "setEntree(), setSide(), and setAccompaniment()"
Step 2:
    If the _subtotal's value is null, subtract the previousEntreePrice from the subtotal. (This explanation corresponds to SetEntree() function)

**Describe the problem**
I think _subtotal.value is never null because the variable gets initialized as soon as OrderViewModel  object is created. Therefore, the variable that should be tested should be _entree.value.

The same goes for setSide and setAccompainment.  

I used _entree.value, _side.value and _setAcompainment and all androidTests were passed successfully.

 
Kind regards,

     Calaudio

**Comment by osuleymanova** [comment]
@Clod 
Thank you for reaching out to us. The typo is fixed and will be published soon:
![Screen Shot 2022-05-19 at 3 56 47 PM](https://user-images.githubusercontent.com/86437155/169613234-d3e8f86c-2068-4f42-aa3d-bf6d053f1f19.png)
