### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by ghs-gs** [google-developer-training/android-basics-kotlin-lunch-tray-app#15]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#0

**In which task and step of the codelab can this issue be found?**

Testing

**Describe the problem**

Order name and other descriptions are not visible in the Check Out page. Only price information is passed correctly.

Prices are set correctly but food info is not visible. I think that I did not manage to pass specific MenuItem data within Datasource class to _entree. 

I tried many ways but I could not make it work. Could you please help me?

Thanks in advance. The details are as follows:

I think I am doing something incorrectly in the view model when I try to set _entree.value. I am setting _entree.value in the ViewModel  function like that:

```
fun setEntree(entree: String) {
        // TODO: if _entree.value is not null, set the previous entree price to the current
        //  entree price.

        if (_entree.value != null){

            previousEntreePrice= _entree.value!!.price

            Log.d(TAG,"setEntree if 1 is called")
        }

        // TODO: if _subtotal.value is not null subtract the previous entree price from the current
        //  subtotal value. This ensures that we only charge for the currently selected entree.

        if (_subtotal.value != null){

            _subtotal.value = _subtotal.value!!.minus(previousEntreePrice)

            Log.d(TAG,"setEntree if 2 is called")
        }

        // TODO: set the current entree value to the menu item corresponding to the passed in string

        _entree.value = DataSource.menuItems[entree]

        // TODO: update the subtotal to reflect the price of the selected entree.

        updateSubtotal(_entree.value!!.price)

    }
```

And this is the part of the layout where I set in the radio button:

```
...
        <RadioButton
                    android:id="@+id/skillet"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textAppearance="?attr/textAppearanceBody1"
                    android:text='@{viewModel.menuItems["skillet"].name}'
                    android:checked='@{viewModel.entree.name.equals(viewModel.menuItems["skillet"].name)}'
                    android:onClick='@{() -> viewModel.setEntree("skillet")}'
                    tools:text="Entree 4" />
...

```
Finally this is the part from the order check out layout:

```
...
            <TextView
                android:id="@+id/entree_selection"
                style="@style/Widget.LunchTray.TextView.CheckoutItem.Info"
                android:text='@{viewModel.entree.name}'
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@id/order_summary"
                tools:text="Cauliflower" />
...

```
**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 2021.1.1.0
_API version of the emulator:_ API 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

You can see the check out page in the emulator like below:

![image](https://user-images.githubusercontent.com/99290613/153071538-8fda40f9-5832-4c14-b194-15bab8052890.png)

As you can see that, prices re summed correctly between each fragment but no any data is visible in the checkout fragment.

**Comment by Gui88** [comment]
Hi, I ran into the same problem, turns out I was missing `viewModel = sharedViewModel` in the onViewCreated in CheckoutFragment.kt

**Comment by ghs-gs** [comment]
Hi, thanks a lot. Same issue in my code, it works right now.
