### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by htoopyaelinn56** [google-developer-training/android-basics-kotlin-lunch-tray-app#18]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Project : Lunch Tray App

**Describe the problem**
Different instrumentation in web and code(comment)

Says subtotal.value is null in website but not null in comment of the code
![Screenshot (54)](https://user-images.githubusercontent.com/85918337/155699927-4ff6fbaa-b670-420f-a684-36940237105a.png)
![Screenshot (55)](https://user-images.githubusercontent.com/85918337/155699932-9ee4d514-cf86-4c8a-a263-30d12e75e771.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@htoopyaelinn56 
Thank you for reaching out to us. The typo is fixed and will be published soon:
![Screen Shot 2022-05-19 at 3 56 47 PM](https://user-images.githubusercontent.com/86437155/169418357-a8514b6e-f556-41b4-9c4f-0b1e974937ff.png)
