### ISSUE TITLE
Android Basics: Lunch Tray app: Conflicting instructions for calculating subtotal.

### ISSUE THREAD

**Issue by profess** [google-developer-training/android-basics-kotlin-lunch-tray-app#24]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
[Project: Lunch Tray app](https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray) Step 3: § setEntree(), setSide(), and setAccompaniment()

**Describe the problem**
The instructions on the page conflict with the instructions given in the TODO within the project, one referring to a positive null test and the other to a negative null test.

Within the CodeLab:
> If the _subtotal's value is null, subtract the previousEntreePrice from the subtotal.

Within the Project:
> // TODO: if _subtotal.value is not null subtract the previous entree price from the current
> //  subtotal value. This ensures that we only charge for the currently selected entree.

**Comment by MadReza** [comment]
It's just bad english and lack of attention on their part.

Here is what I recommend (it is the same for Entree, Side, Ac...:
1- Make previousPrice = the current one.    Of course, if there is none, set to 0.
2- Remove previousPrice from subtotal based on step 1.
3- Make the value be the menuItem element matching the method parameter.
4- Add the price value to subtotal based on step 3.

I tried not giving away too much. good luck.

**Comment by huss-a** [comment]
I decided to follow the `TODO` comments in the project.  Since you can't subtract anything from `null`, it's probably just a mistake in the codelab.

**Comment by osuleymanova** [comment]
@profess 
The issue that you presented to us is important, and I thank you for bringing it to our attention. The typo is fixed and will be published soon:
![Screen Shot 2022-05-19 at 3 56 47 PM](https://user-images.githubusercontent.com/86437155/169418195-0726ca98-2237-4d0a-bf79-366c3b3498d9.png)
