### ISSUE TITLE
Android Basics: Lunch Tray app | Build Failing

### ISSUE THREAD

**Issue by huss-a** [google-developer-training/android-basics-kotlin-lunch-tray-app#25]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
Building project with compileSdkVersion & targetSdkVersion 31

**Describe the problem**
The project build produces errors:
```
/home/USER/code/AndroidStudioProjects/android-basics-kotlin-lunch-tray-app/app/src/main/AndroidManifest.xml:27:9-33:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
/home/USER/code/AndroidStudioProjects/android-basics-kotlin-lunch-tray-app/app/src/main/AndroidManifest.xml:34:9-40:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
/home/USER/code/AndroidStudioProjects/android-basics-kotlin-lunch-tray-app/app/src/main/AndroidManifest.xml:41:9-47:20 Error:
	android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
```
As stated in the error, I set the `android:exported` value to `true`, but it still produces the same error.

**Steps to reproduce?**
1. Set the targetSdkVersion & compileSdkVersion to 31
2. Build the project

**Versions**
_Android Studio version:_ Android Studio Bumblebee | 2021.1.1 Patch 2 Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
_API version of the emulator:_ 30

**Comment by amoralesc** [comment]
Did you manage to solve the problem? I can't build the project neither. I have set targetSdkVersion and compileSdkVersion to 31 and 32, but failed to build anyways. After setting the property `android:exported` to `true` in the manifest, I get the following errors building:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugResources'.
```
```
Unexpected character '[' (code 91) expected '='
 at [row,col {unknown-source}]: [61,26]
```

**Android Studio version:**
Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
**API version of the emulator:** 30
