### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by LoyalRoad** [google-developer-training/android-basics-kotlin-lunch-tray-app#29]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-5%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**

3. Get Started
**Describe the problem**

I think this code must be if not null but you wrote it "If the _subtotal's value is null, subtract the previousEntreePrice from the subtotal."
since if it is null which is false since it initialized already with 0.0 then the condition will never be met!
so it should be if not is null here is an example
        if (_subtotal.value != null) {
            _subtotal.value = _subtotal.value?.minus(previousEntreePrice)
        }
I think you correct that condition in your comment in the Lunch Tray app. in OrderViewModel.kt
because once 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@LoyalRoad 
Thank you for reaching out to us. The typo is fixed and will be published soon:
![Screen Shot 2022-05-19 at 3 56 47 PM](https://user-images.githubusercontent.com/86437155/169418008-91477f41-6385-4188-b780-69aea9c134fa.png)
