### ISSUE TITLE
Android Basics: Lunch Tray app (What is the best way to set onCLick for buttons?)

### ISSUE THREAD

**Issue by SonOfaSleep** [google-developer-training/android-basics-kotlin-lunch-tray-app#37]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
Hello! 
I have a question about click listener for buttons in layout files. What is the best way to call method in layout?
For example in `fragment_entree_menu.xml` i want to set onClick listener for `setEntree` method, but it needs string with name of the entree dish for it.

I've come up only with creating variables in xml with String type and initialize them in `EntreeMenuFragment`.

Is there a better way to pass string to `setEntree`?

Screenshots of what i meen:

<img width="1437" alt="onClick" src="https://user-images.githubusercontent.com/86229067/184898889-64ece4af-48fe-4e48-8483-6d9fbe7babda.png">
<img width="1436" alt="Variables" src="https://user-images.githubusercontent.com/86229067/184898896-8e827462-f160-4437-9703-a831e779407d.png">
<img width="1439" alt="VerInit" src="https://user-images.githubusercontent.com/86229067/184898912-97e2793f-8c23-4fdc-9fa5-27a2e878ca23.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by abdellatifdarmellah** [comment]
I did the same but I don't think it's the right method

**Comment by Chaitanya-kamra** [comment]
use string resource
add all these strings in stings.xml
like:@string\cauliflower

**Comment by ZSnowbank** [comment]
If you use single quotes around the whole attribute assignment, you can then use double quotes inside of it. So for example
`android:onClick='@{() -> viewModel.setEntree("skillet")}'`
I doubt the original poster still needs this, but just in case anyone comes here looking for the answer, here it is.
