### ISSUE TITLE
Missing information in Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by s205358** [google-developer-training/android-basics-kotlin-lunch-tray-app#4]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
Get started

**Describe the problem**
Will report the issue here as I can't find anywhere else to.

There is no mention of the TODO in main_activity.xml in the Codelab.

Because the target audience for this Codelab is beginners and the Codelabs in the Android Basics in Kotlin course have no mention of the built-in TODO feature in Android Studio, beginners will struggle to find out how to resolve the issue of running the program when retrieving the NavController in MainActivity.kt. Note: I am aware that the projects are meant to give the "student" some experience on their own, i.e. not hold their hand, but considering the format of this project and former projects, I don't think not mentioning that TODO as opposed to all other TODOs make any sense.

**Comment by s205358** [comment]
Additionally, there is no mention of the strings used for formatting the subtotal, tax, and total in the fragment_checkout.xml.

**Comment by Generic-droid** [comment]
If you follow step by step as recommended, there will be no issues. Everything that you wrote was mentioned in the previous codelabs.

**Comment by s205358** [comment]
> If you follow step by step as recommended, there will be no issues. Everything that you wrote was mentioned in the previous codelabs.

There is now, but I am almost certain that there wasn't at the time of writing, i.e. the day it was added on which I could find no mentions of "activity_main.xml" using CTRL + F as opposed to now. :)
