### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by bricohen88** [google-developer-training/android-basics-kotlin-lunch-tray-app#7]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#4

**In which task and step of the codelab can this issue be found?**
testing

**Describe the problem**

In the NavigationTests file several tests refer destination with R.id.startOrder which does not exist. I believe it should be R.id.startOrderFragment. Everything seems to function fine after this small change.

**Steps to reproduce?**
1. Go to... NavigationTests
2. Click on...
3. See error... all the functions clicking the cancel button

**Versions**
_Android Studio version:_ 2020.3.1
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Generic-droid** [comment]
The same issue.

**Comment by JerryMtezH** [comment]
I have the same issue 
![issue startOrder](https://user-images.githubusercontent.com/19557433/142072683-6639a4b9-7192-443a-a6ec-f13873f4363d.png)

**Comment by alu0100207385** [comment]
Hi guys,

I also had the same issue. It seems it is referring to the navigation id. If you (like me) used the navigation UI to generate the navigation graph the id is 'startOrderFragment'. So, to fix that, in you navigation XML file, change this id with 'startOrder' and now, it should work.

**Comment by nyklm** [comment]
In the test rename **_R.id.startOrder_** to **_R.id.startOrderFragment_**. That's all.
