### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by Generic-droid** [google-developer-training/android-basics-kotlin-lunch-tray-app#8]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
Step 3 "Get Started"

**Describe the problem**
There is a typo in:

2. If the _subtotal's **value is null**(is null, really?), subtract the previousEntreePrice from the subtotal.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Generic-droid 
Thank you for reaching out to us. The typo is fixed and will be published soon:
![Screen Shot 2022-05-19 at 3 56 47 PM](https://user-images.githubusercontent.com/86437155/169420262-3f59673d-b3c2-4245-ba70-bba6dcc944a1.png)
