### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by LucaBini93** [google-developer-training/android-basics-kotlin-lunch-tray-app#9]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
Section:
setEntree(), setSide(), and setAccompaniment()

**Describe the problem**
Point 2:
2. If the _subtotal's value is **not** null, subtract the previousEntreePrice from the subtotal.

"not" word missing

**Comment by osuleymanova** [comment]
@LucaBini93 
Thank you for reaching out to us. The typo is fixed and will be published soon:
![Screen Shot 2022-05-19 at 3 56 47 PM](https://user-images.githubusercontent.com/86437155/169420330-027b8730-c806-49f0-b844-143a06f6933b.png)
